assign_web_broker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('eapp.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eapp/urls.py
from django.urls import path

from eapp.views import ProductListView, ProductDetailView, ProductOrderView

app_name = "eapp"
urlpatterns = [
    path('product/list', ProductListView.as_view(), name='productlist'),
    path('product/<int:pk>/order', ProductDetailView.as_view(), name='productdetail'),
    path('order/product/id/<int:pk>', ProductOrderView.as_view(), name='orderproduct')
]

eapp/models.py
from django.db import models


# Create your models here.
class Product(models.Model):
    title = models.CharField(max_length=255)
    images = models.ImageField(upload_to='media')
    category = models.CharField(max_length=50)
    price = models.FloatField()

    def __str__(self):
        return self.title


class Order(models.Model):
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=10)

    def __str__(self):
        return self.name

eapp/forms.py
from django import forms

from eapp.models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = "__all__"
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
            }),

            'phone': forms.TextInput(attrs={
                'class': 'form-control',
            })
        }

eapp/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import ListView, DetailView, CreateView
from twilio.base.exceptions import TwilioRestException
from twilio.rest import Client
from eapp.forms import OrderForm
from eapp.models import Product
from eapp.tasks import new_order


class ProductListView(ListView):
    template_name = 'clienttemplates/packagelist.html'
    queryset = Product.objects.all().order_by('-id')
    context_object_name = 'itemlist'
    paginate_by = 6


class ProductDetailView(DetailView):
    template_name = 'clienttemplates/packagedetail.html'
    model = Product
    context_object_name = 'item'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['order_form'] = OrderForm
        return context


class ProductOrderView(CreateView, SuccessMessageMixin):
    template_name = 'clienttemplates/packagedetail.html'
    form_class = OrderForm
    success_message = "Thank You for ordering. Your order has been placed Successfully"

    def form_valid(self, form):
        name = form.cleaned_data['name']
        phone = form.cleaned_data['phone']

        new_order.delay(name, phone)

        account_sid = 'AC3cbfa74e4e206083aa8763abca8ac344'
        auth_token = '1bfe85c8a97690da6dc26647ccf19eb7'
        client = Client(account_sid, auth_token)

        try:
            message = client.messages.create(to="+977" + phone, from_="981927990", body="Dear CUstomer, Your order "
                                                                                        "has been successfully placed")
        except TwilioRestException as e:
            print(e)

        return super().form_valid(form)

    def get_success_url(self):
        return "/product/" + str(self.kwargs['pk']) + "/order"

templates/clienttemplates/clientbase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %} {% endblock %}</title>

    <!-- Plugins CSS -->
    
	<link rel="stylesheet" href="{% static 'clientstatic/plugins/css/plugins.css' %}">	
    
    <!-- Custom style -->
    <link href="{% static 'clientstatic/css/style.css' %}" rel="stylesheet">
	<link href="{% static 'clientstatic/css/responsiveness.css' %}" rel="stylesheet">
	<link id="jssDefault" rel="stylesheet" href="{% static 'clientstatic/css/skins/default.css' %}">

	{% block link %}  {% endblock %}
	
	<style>

			#snackbar {
			  visibility: hidden;
			  min-width: 250px;
			  margin-left: -125px;
			  background-color: #FF5430;
			  color: #ffffff;
			  text-align: center;
			  border-radius: 2px;
			  padding: 16px;
			  position: fixed;
			  z-index: 1;
			  left: 50%;
			  bottom: 53px;
			  font-size: 17px;

			}

			#snackbar.show {
			  visibility: visible;
			  -webkit-animation: fadein 0.5s, fadeout 0.5s 2.5s;
			  animation: fadein 0.5s, fadeout 0.5s 2.5s;
			}

			@-webkit-keyframes fadein {
			  from {bottom: 0; opacity: 0;} 
			  to {bottom: 30px; opacity: 1;}
			}

			@keyframes fadein {
			  from {bottom: 0; opacity: 0;}
			  to {bottom: 30px; opacity: 1;}
			}

			@-webkit-keyframes fadeout {
			  from {bottom: 30px; opacity: 1;} 
			  to {bottom: 0; opacity: 0;}
			}

			@keyframes fadeout {
			  from {bottom: 30px; opacity: 1;}
			  to {bottom: 0; opacity: 0;}
			}

		
	</style>


	</head>
	
	<body>
	
		<!-- ======================= Start Navigation ===================== -->
		<nav class="navbar navbar-default navbar-mobile navbar-fixed light bootsnav">
			<div class="container">
			
				<!-- Start Logo Header Navigation -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
						<i class="fa fa-bars"></i>
					</button>
					<a class="navbar-brand" href="">
						<img src="{% static 'clientstatic/img/logo.png' %}" class="logo logo-scroll" style="max-height: 50px; width: 100%; object-fit: contain;"> 
						<img src="{% static 'clientstatic/img/logo.png' %}" class="logo logo-display" style="max-height: 50px; width: 100%; object-fit: contain;">
					</a>

				</div>
				<!-- End Logo Header Navigation -->

				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="navbar-menu">
				
					<ul class="nav navbar-nav navbar-left" data-in="fadeInDown" data-out="fadeOutUp">
					
						<li class="{% block homepage %}{% endblock %} ">
							<a href="">Home</a>
							
						</li>
						<!-- <li class="dropdown {% block packagelist %}{% endblock %}">

							
						<li class="{% block service %}{% endblock %}">
							<a href="">Services</a>
							
						</li>
					

						<li class="{% block albumlist %}{% endblock %}">
							<a href="">Categories</a>
							
						</li>
					
						<li class ="{% block productlist %}{% endblock %}">
							<a href="{% url 'eapp:productlist' %}" >Products</a>
							
						</li>
						<li class ="{% block aboutus %}{% endblock %}">
							<a href="">About us</a>
							
						</li>
																				
									
					</ul>
					
					<ul class="nav navbar-nav navbar-right">
						<li class="{% block contactus %}{% endblock %}"><a class="btn-signup red-btn" href=""><span class="ti-briefcase"></span>Contact Us</a></li> 
					</ul>
						
				</div>
				<!-- /.navbar-collapse -->
			</div>  
		</nav>
		<!-- ======================= End Navigation ===================== -->
{% block content %}   {% endblock %}

		
		{% if messages %}
			<div id="snackbar">
				{% for m in messages %}
					{{ m}}
				{% endfor %}
			</div>
			
		{% endif %}

		
		 
		<!-- =================== START JAVASCRIPT ================== -->
		<script src="{% static 'clientstatic/plugins/js/jquery.min.js' %}"></script>
		<script src="{% static 'clientstatic/plugins/js/bootstrap.min.js' %}"></script>
		<script src="{% static 'clientstatic/plugins/js/viewportchecker.js' %}"></script>
		<script src="{% static 'clientstatic/plugins/js/bootsnav.js' %}"></script>
		<script src="{% static 'clientstatic/plugins/js/slick.min.js' %}"></script>
		<script src="{% static 'clientstatic/plugins/js/jquery.nice-select.min.js' %}"></script>
		<script src="{% static 'clientstatic/plugins/js/jquery.fancybox.min.js' %}"></script>
		<script src="{% static 'clientstatic/plugins/js/jquery.downCount.js' %}"></script>
		<script src="{% static 'clientstatic/plugins/js/freshslider.1.0.0.js' %}"></script>
		<script src="{% static 'clientstatic/plugins/js/moment.min.js' %}"></script>
		<script src="{% static 'clientstatic/plugins/js/daterangepicker.js' %}"></script>
		<script src="{% static 'clientstatic/plugins/js/wysihtml5-0.3.0.js' %}"></script>
		<script src="{% static 'clientstatic/plugins/js/bootstrap-wysihtml5.js' %}"></script>
		
		<!-- Dashboard Js -->
		<script src="{% static 'clientstatic/plugins/js/jquery.slimscroll.min.js' %}"></script>
		<script src="{% static 'clientstatic/plugins/js/jquery.metisMenu.js' %}"></script>
		<script src="{% static 'clientstatic/plugins/js/jquery.easing.min.js' %}"></script>
 
		<!-- Custom Js -->
		<script src="{% static 'clientstatic/js/custom.js' %}"></script>
		
		<script src="{% static 'clientstatic/js/jQuery.style.switcher.js' %}"></script>
		<script>
			function openRightMenu() {
				document.getElementById("rightMenu").style.display = "block";
			}
			function closeRightMenu() {
				document.getElementById("rightMenu").style.display = "none";
			}
		</script>

		<script type="text/javascript">
			$(document).ready(function() {
				$('#styleOptions').styleSwitcher();
			});
		</script>

		<script>
			$(document).ready(function(){
			  var x = document.getElementById("snackbar");
			  x.className = "show";
			  setTimeout(function(){ x.className = x.className.replace("show", ""); }, 3000);
			})
		</script>

		{% block script %}
		 {% endblock %}

	
    </body>

</html>

templates/clienttemplates/packagedetail.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}
{% block productlist %}active{% endblock %}

{% block content %}

    <div class="page-title image-title"
         style="background-image:url({% static 'clientstatic/img/sli00.jpg' %}); height: 350px; object-fit: contain;">
    </div>
    <section class="tr-single-detail gray-bg">
        <div class="container">
            <div class="row">

                <div class="col-md-6 col-sm-12 mx-3">
                    <div class="tab-content tabs">

                        <!-- Overview -->
                        <div class="row">
                            <div class="tr-single-box">
                                <div class="tr-single-header">
                                    <h4><i class="fa fa-star-o"></i>Overview</h4>
                                </div>
                                <div class="tr-single-body">
                                    <div class="row">
                                        <div class="col-md-6 col-sm-6">
                                            <div class="list-thumb-box">
                                                <img src="{{ item.image.url }}" class="img-responsive" alt=""/>
                                            </div>
                                        </div>

                                        <div class="col-md-6 col-sm-6">
                                            <div class="list-overview-detail">
                                                <h4>{{ item.title }}</h4>
                                                <ul class="extra-service">
                                                    <li>
                                                        <div class="icon-box-icon-block">
                                                            <div class="icon-box-round">
                                                                <i class="ti-headphone-alt"></i>
                                                            </div>
                                                            <div class="icon-box-text">
                                                                {{ item.category }}
                                                            </div>
                                                        </div>
                                                    </li>
                                                    <li>
                                                        <div class="icon-box-icon-block">
                                                            <div class="icon-box-round">
                                                                <i class="ti-user"></i>
                                                            </div>
                                                            <div class="icon-box-text">
                                                                Rs.{{ item.price }}
                                                            </div>
                                                        </div>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>


                        </div>


                    </div>
                </div>


                <div class="col-md-6 col-sm-12">
                    <div class="form-box">
                        <form class="c-form" action="{% url 'eapp:orderproduct' item.id %}" method="POST">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-sm-12">
                                    <label>Name<sup class="cl-danger">*</sup></label>
                                    {{ order_form.name }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <label>Phone<sup class="cl-danger">*</sup></label>
                                    {{ order_form.phone }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <button type="submit" class="btn theme-btn btn-arrow">Order</button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>



{% endblock %}

templates/clienttemplates/packagelist.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}

{% block productlist %}active{% endblock %}

{% block content %}
	
	<div class="page-title image-title" style="background-image:url({% static 'clientstatic/img/sli00.jpg' %}); height: 350px; object-fit: contain;">
		<div class="container">
			
		</div>
	</div>

	<section class="gray-bg">
		<div class="container">
			<div class="row">	
			<!-- Single Destination -->
				{% for item in itemlist %}

					<div class="col-md-4 col-sm-6">
						<article class="tour-box style-1" style="width: 320px;">
							
							<!-- Single Tour -->
							<div class="tour-box-image">
								<figure>
									<a href="">
										<img src="{{item.image.url}}" class="img-responsive listing-box-img" alt="" />
										<div class="list-overlay"></div>
									</a>
									
								</figure>
							</div>
							
							<div class="inner-box">
								<div class="box-inner-ellipsis">
									<h4 class="hotel-name">
										{{item.title}} </a>
									</h4>
									<div class="price-box">
										<div class="tour-price fl-right">
										{% if item.price %}
											<i class="fa fa-rupee"></i><span class="theme-cl f-bold">{{item.price}}</span>
										{% endif %}
										</div>
									</div>

								</div>
							</div>
							<a href="{% url 'eapp:productdetail' item.id %}" class="btn btn-wow theme-btn orderbutton">
							 Order
							</a>

						</article>

					</div>

					{% endfor %}
				</div>

				<div class="row">
				<div class="col-md-12">
					<div class="bs-example">
					{% if is_paginated %}
						<ul class="pagination">
						{% if page_obj.has_previous %}
							<li class="page-item">
					  			<a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
									<span class="ti-arrow-left"></span>
									<span class="sr-only">Previous</span>
					  			</a>
							</li>
						{% else %}
							<li class="disabled">
								<span class="ti-arrow-left"></span>
							</li>
						{% endif %}
						{% for i in paginator.page_range %}
							{% if page_obj.number == i %}
								<li class="page-item active">
									<span class="sr-only">{{i}}</span>
								</li>
							{% else %}
								<li><a href="?page={{ i }}">{{ i }}</a></li>
							{% endif %}
						{% endfor %}
			
						{% if page_obj.has_next %}
							<li class="page-item"> 
								<a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Next">
									<span class="ti-arrow-right"></span>
									<span class="sr-only">Next</span>
							  </a>
							</li>
						{% else %}
							<li class="disabled"><span class="ti-arrow-right"></span>
							
						{% endif %}
					
						</ul>
					{% endif %}
					</div>
				</div>
			</div>

				
			</div>
		</section>
				
		

{% endblock %}

{% block script %}  

<script>
	
	$(document).on('click', '.orderbutton', function() {
		retry_order(5, $(this));
});


		function retry_order(retryfor, selector) {
			var get_url = selector;
			$.ajax({

				url: get_url.attr('href'),
				type: 'GET',
				success: function (data) {
					console.log('data')
					return false;
				},
				error: function (err){
					
					while (retryfor != 0){
						retry_order(retryfor, selector);
						console.log('retrying...');
						console.log(retryfor);
						retryfor = retryfor-1
					}
				},
			});
			
			

		}
		

</script>	

{% endblock %}